name: Deploy Azure Function (Python)

on:
  push:
    branches:
      - main  # Ajuste para o branch que aciona o deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ajuste conforme a versão usada no seu app

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Function
      run: |
        func azure functionapp publish ${{ secrets.AZURE_FUNCTIONAPP_NAME }} --python
