name: Deploy Azure Function (Python)

on:
  push:
    branches:
      - main  # Nome do branch que dispara o workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar a versão do Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    # 3. Instalar as dependências do Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Fazer login no Azure com as credenciais
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: >
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    # 5. Publicar a Azure Function
    - name: Deploy Azure Function
      uses: azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: '.'
